# Example configuration file for the Recall Data Synchronizer

# PostgreSQL database configuration (source of object metadata)
[database]
url = "postgresql://recall:recall_password@localhost:5432/recall_competitions"
max_connections = 5
connect_timeout_seconds = 3

# SQLite configuration (for synchronizer state)
[sync_storage]
path = "data/sync_state.db"

# S3 configuration
[s3]
endpoint_url = "https://s3.amazonaws.com"
region = "us-east-1"
access_key_id = "YOUR_ACCESS_KEY"
secret_access_key = "YOUR_SECRET_KEY"
bucket_name = "competition-data"

# Recall network configuration
[recall]
node_url = "https://node.example.com"
signer_key = "YOUR_PRIVATE_KEY"

# Synchronization settings
[sync]
interval_seconds = 60
batch_size = 100
max_retries = 3
retry_delay_seconds = 5