# Configuration file for the Recall Data Synchronizer

# PostgreSQL database configuration (source of object metadata)
[database]
url = "postgresql://recall:recall_password@localhost:5432/recall_competitions"
max_connections = 5

# SQLite configuration (for synchronizer state)
[sync_storage]
path = "data/sync_state.db"

# S3 configuration
[s3]
endpoint = "http://localhost:9000"
region = "us-east-1"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"
bucket = "recall-bucket"

# Recall network configuration
[recall]
private_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
network = "localnet"
config_path = "networks.toml"

# Synchronization settings
[sync]
batch_size = 100
state_db_path = "./sync_state.db"