[database]
url = "postgresql://recall:recall_password@localhost:5432/recall_competitions"
max_connections = 5

[s3]
endpoint = "http://localhost:9000"
region = "us-east-1"
bucket = "recall-bucket"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"

[recall]
network = "localnet"
config_path = "networks.toml"
private_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"

[sync]
batch_size = 100

[sync_storage]
db_path = "./sync_state.db"