services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: recall
      POSTGRES_PASSWORD: recall_password
      POSTGRES_DB: recall_competitions
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recall"]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 5

  recall:
    image: textile/recall-localnet:latest
    ports:
      - "127.0.0.1:8545:8545"  # Ethereum RPC port
      - "127.0.0.1:8645:8645"  # Recall EVM RPC port
      - "127.0.0.1:8001:8001"  # Object API port
      - "127.0.0.1:26657:26657"  # CometBFT RPC port
    volumes:
      - recall_data:/data
    privileged: true  # Required for Docker-in-Docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8545"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  minio_data:
  recall_data: