version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: recall
      POSTGRES_PASSWORD: recall_password
      POSTGRES_DB: recall_competitions
    ports:
      - "5432:5432"
    volumes:
      - ./schema:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recall"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: