[database]
enabled = false
url = "postgresql://recall:recall_password@localhost:5432/recall_competitions"

[sqlite]
enabled = false
path = ""

[s3]
enabled = false
endpoint = "http://localhost:9000"
region = "us-east-1"
bucket = "test-bucket"
access_key_id = "minioadmin"
secret_access_key = "minioadmin"

[recall]
enabled = false
network = "localnet"
config_path = "networks.toml"
private_key = "ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"