name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_NET_GIT_FETCH_WITH_CLI: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          components: rustfmt, clippy

      - name: Build
        run: make build

      - name: Run linter
        run: make lint

      - name: Run tests
        run: make test

      - name: Get version from Cargo.toml
        id: get_ver
        uses: dante-signal31/rust-app-version@v1.2.0

      - name: Tag
        uses: actions/github-script@v5
        id: create-tag
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.get_ver.outputs.app_version }}',
              sha: context.sha
            })

      - name: Publish
        run: >
          cargo publish
          --verbose
          --workspace
          --locked
          --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Release 🚀
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.get_ver.outputs.app_version }}
          generateReleaseNotes: true
          prerelease: ${{ contains(steps.get_ver.outputs.app_version, 'pre') }}
          token: ${{ secrets.GITHUB_TOKEN }}
